# Generated by Django 4.2.5 on 2023-12-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0002_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='snaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snap_name', models.CharField(default='img', max_length=255)),
                ('snap', models.FileField(null=True, upload_to='')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
