# Generated by Django 4.2.5 on 2023-12-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='file', max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
