# Generated by Django 4.2.5 on 2023-12-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='file',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='text',
            field=models.TextField(blank=True, default='text'),
        ),
    ]
