# Generated by Django 4.2.7 on 2023-12-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_notifications_file_alter_notifications_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='enrolled_as',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
