# Generated by Django 4.2.5 on 2023-12-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_classroom_enrolled_as_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='text',
            field=models.TextField(blank=True, default='text', null=True),
        ),
    ]
