# Generated by Django 4.2.5 on 2023-12-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_notifications_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='text',
        ),
        migrations.AddField(
            model_name='notifications',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notifications',
            name='file_name',
            field=models.CharField(default='file', max_length=50),
        ),
    ]
