# Generated by Django 4.2.5 on 2023-12-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='file', max_length=50)),
                ('item_photo', models.FileField(null=True, upload_to='')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
