# Generated by Django 4.2.5 on 2023-12-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_desc',
            field=models.TextField(default='watch downloaded from internet'),
            preserve_default=False,
        ),
    ]
