# Generated by Django 4.2.5 on 2023-12-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
