# Generated by Django 4.2.7 on 2023-12-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usermodel_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
